version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: server_arch_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: server_architect
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: server_arch_redis
    ports:
      - "6379:6379"

  neo4j:
    image: neo4j:latest
    container_name: server_arch_neo4j
    environment:
      NEO4J_AUTH: neo4j/neo4jpassword
    ports:
      - "7474:7474" # واجهة التحكم
      - "7687:7687" # منفذ Bolt

volumes:
  pgdata: